name: Unity_Multi-Platform_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        targetPlatform: [StandaloneWindows64, Android, iOS] # Platforms to build

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Unity
      - name: Set up Unity
        uses: game-ci/unity-setup@v3
        with:
          unityVersion: 2023.1.12f1 # Update to match your Unity version
          activationMethod: github

      # Cache Unity Library
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ matrix.targetPlatform }}-${{ hashFiles('**/*') }}

      # Build the Unity project
      - name: Build for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: .

      # Upload the build artifact
      - name: Upload Build Artifact for ${{ matrix.targetPlatform }}
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
